travis:
  secure:
    BINSTAR_TOKEN: qBCIa/Hy3f2mbmYdbfAB1Vy/HXEbe9xRJBi25+2GHQhOtM/gZw3SkMYUqYcJeS1nPqdJfBpCb66EbVetRxuzR3bLwWIEWzO/peyUOogQTt70t5yQ0Wzs/sBrHICQfrhphCGy0N/WZ6vkdVctkGpMw7ZzLU70uxlD97UF2k4ubeaaDfFn1aEX8+Yc1IqcKm+M9U7bARg6jVS3T1U6LKH8o3TANnexD7i+7hG1z3sgt9yfkbdplujCICgkaVQ8ZT3r+23ssRnQxZ98PP61noYpVG9Tf+ppBudD6+HzteGW2+8VHXnNYqqJyLjNcpfe2ROG/cy6uQRAawbn/1aVip1ys0Ll1nnMpKLDlvbjjDO1G2dkV34eE42CtuB91C1M0mkCJybyM37Fq5a9z104u64sUj8PyOZ3N+uMxkUllt35jySNVEu69w9wErUBd+5k7mcFAU6422Z2moONVsTto+z1D6Kz99YefR7LtIQi0KXdjkWQqkFe+LsGFk1mPuJET4bLoSWZ39eoOWVD9VbzuthbIC07DsF4CcY+Fn55Os2jOcmtkTuCQBOv1JlaWlQWtUm93dDb0qsv329ONrh+2uC+B24X6BfKKzYIh3C1z4rsgvGR2/xc81V3QN3pHA05l6/kYhBYQy0/QMg9yEfbBBZDFEha56JLjpZZHu6yOha0RJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
